/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Day = IDL.Record({
  'name' : IDL.Text,
  'transliteration' : IDL.Text,
});
export const Month = IDL.Record({
  'name' : IDL.Text,
  'transliteration' : IDL.Text,
});

export const idlService = IDL.Service({
  'getCurrentTime' : IDL.Func([], [IDL.Int], []),
  'getDays' : IDL.Func([], [IDL.Vec(Day)], ['query']),
  'getMonths' : IDL.Func([], [IDL.Vec(Month)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Day = IDL.Record({ 'name' : IDL.Text, 'transliteration' : IDL.Text });
  const Month = IDL.Record({ 'name' : IDL.Text, 'transliteration' : IDL.Text });
  
  return IDL.Service({
    'getCurrentTime' : IDL.Func([], [IDL.Int], []),
    'getDays' : IDL.Func([], [IDL.Vec(Day)], ['query']),
    'getMonths' : IDL.Func([], [IDL.Vec(Month)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };